[package]
name = "fuss-rs"
version = "0.1.0"
authors = ["James Wilson <me@unbui.lt>"]

[dependencies]
pest = "1.0.0-beta.15"
pest_derive = "1.0.0-beta.15"
clap = {version = "2.26", features = ["yaml"]}